apiVersion: v1
kind: Service
metadata:
  name: surl-main
  namespace: default
  labels:
    app: surl-main
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
  selector:
    app: surl-main